Fix/legacy app scrolling
AdaloHQ/calendar pull request #49
Opened 2023-12-20 14:34 UTC by itsdaiego

## Problem

Previously we pushed changes that prevented the Calendar View (day view) to fill up the entire screen, which is good but with that a new regression was created where in  legacy (ios/android), it affects other platforms as well

## Solution

After trying a few things I realized that I needed to create a container where IT has a fixed height and then the scrollable area would have the entire calendar options height (2400). 

After doing that for some reason the scrollable area didn't go till the very end, so I couldn't see the end of it, I setup a deadline for myself and since I couldn't pinpoint what it was (although I noticed similar things happening in previous versions of the component) I added an extra padding 100 (each hour in the screen accounts for 100 so I'm basically adding space for one more hour).

This seem to work across all platforms (ios/android) and targets (responsive/legacy/pwa), the only exception is ios pwa where I can't see any events and instead I see a quick "flash" to what would be the event and then it disappears, it appears that this bug always existed since I can reproduce it even on version 1.0.0.

Video:

https://github.com/AdaloHQ/calendar/assets/4576630/4ca74791-73b4-4195-ab2d-d01502fdf686

2023-12-20 16:16 UTC, itsdaiego commented
![](https://github.trello.services/images/mini-trello-icon.png) [Calendar | Calendar component scroll not working | 3 November 2023](https://trello.com/c/KtZbwA7s/658-calendar-calendar-component-scroll-not-working-3-november-2023)

2023-12-21 10:45 UTC, michael-adalo approved these changes
✅ NOICE

<img src="https://media.giphy.com/media/xTiQywlOn0gKyz0l56/giphy.gif"/>

2023-12-22 17:11 UTC, danicunhac approved these changes

2024-01-15 20:39 UTC, michael-adalo requested changes
Code looks fine to me, but blocking merge until we've investigated the possibility that a deprecated lifecycle hook isn't being run anymore.

2024-01-15 20:39 UTC, michael-adalo commented on src/components/DynamicCalendar/eventCal/EventCalendar.js
> +    }
would it be worth encapsulating this into its own function or memoizing the value?  I see we're using the componentWillReceiveProps (which is deprecated, but could be useful in this case to set the filtered value in state prior to render?)

2024-01-15 20:39 UTC, michael-adalo commented on src/components/DynamicCalendar/eventCal/DayView.js
>    componentWillReceiveProps(nextProps) {
https://legacy.reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

This lifecycle hook is deprecated and from what the documentation says, the non-prefixed version probably isn't being executed in React 17 and 18 (we're using React 18 for native and web rendering of our applications now, though significantly not in builder).

That said, perhaps our use of React Native and React Native Web means it's still running?  I'm honestly not sure.

Would it be worth adding the `UNSAFE_` prefix and re-testing?

2024-01-16 14:56 UTC, michael-adalo approved these changes
✅  NOICE, thanks for taking a look at that lifecycle hook...

2024-01-16 17:31 UTC, merged